modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/pau101/Wings/issues"
license = "MIT"
[[mods]]
modId = "wings"
version = "${version}"
displayName = "Wings"
displayURL = "https://minecraft.curseforge.com/projects/wings"
authors = "pau101"
description = "The Wings mod introduces an assortment of avian and insectoid wings for all of your aerial travel needs."
logoFile = "logo.png"
[[dependencies.wings]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,1.17)"
ordering = "NONE"
side = "BOTH"
